### ISSUE TITLE
MovSim JavaDocs

### ISSUE THREAD

**Issue by Aaqiba** [movsim/movsim#32]
Hi! We are beginner in MOVSIM. Can we have documentation of MOVSIM?

**Comment by MTGermany** [comment]
Dear Mr/Ms Aaqiba,

there is no formal documentation in form of a User's Manual or Tech 
Manual. However, Arne Kesting (see the cc) who is the main developer, 
surely has some general comments on the global structure. Regarding 
details, the code itself is commented, according to the principle "the 
truth lies in the code"

Regards

Martin

----------------------------------------------------------
Dr. Martin Treiber
          Institute for Transport & Economics, TU Dresden
	 Chair of Traffic Modelling, Econometrics, and Statistics
          Falkenbrunnen, Room 123 (two floors up from the entrance!)
          Würzburger Str. 35, D-01062 Dresden
          treiber@vwi.tu-dresden.de,
          www.mtreiber.de
          phone/fax:     +49 (351) 463 36794 / 36809
  ---------------------------------------------------------

**Comment by Aaqiba** [comment]
These links on your website (http://www.movsim.org/) for
MovSim Javadocs (
http://www.h2063376.stratoserver.net/movsim/version/current/apidocs/index.html
)
Routing
Ramp metering
these are not working.
help us?

On Thu, Mar 3, 2016 at 3:09 PM, MTGermany <notifications@github.com> wrote:

> Dear Mr/Ms Aaqiba,
>
> there is no formal documentation in form of a User's Manual or Tech
> Manual. However, Arne Kesting (see the cc) who is the main developer,
> surely has some general comments on the global structure. Regarding
> details, the code itself is commented, according to the principle "the
> truth lies in the code"
>
> Regards
>
> Martin
>
> ----------------------------------------------------------
> Dr. Martin Treiber
> Institute for Transport & Economics, TU Dresden
> Chair of Traffic Modelling, Econometrics, and Statistics
> Falkenbrunnen, Room 123 (two floors up from the entrance!)
> Würzburger Str. 35, D-01062 Dresden
> treiber@vwi.tu-dresden.de,
> www.mtreiber.de
> phone/fax: +49 (351) 463 36794 / 36809
> ---------------------------------------------------------
>
> On 03/03/2016 07:35 AM, Aaqiba wrote:
> >
> > Hi! We are beginner in MOVSIM. Can we have documentation of MOVSIM?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/movsim/movsim/issues/32>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movsim/movsim/issues/32#issuecomment-191692165>.
>



-- 
Regards
Team Learning for Optimal Driver's Personality Profile

**Comment by MTGermany** [comment]
Hello Aqiba,

I have forwarded this mail to Arne who runs this website.

Arne: Some links on the page www.movsim.org -> about, for example 
"MovSim JavaDocs", and nearly all of the links on the "examples" page do 
not work (dead link or "denial of response")

Martin

----------------------------------------------------------
Dr. Martin Treiber
          Institute for Transport & Economics, TU Dresden
	 Chair of Traffic Modelling, Econometrics, and Statistics
          Falkenbrunnen, Room 123 (two floors up from the entrance!)
          Würzburger Str. 35, D-01062 Dresden
          treiber@vwi.tu-dresden.de,
          www.mtreiber.de
          phone/fax:     +49 (351) 463 36794 / 36809
  ---------------------------------------------------------

**Comment by Aaqiba** [comment]
Thank you for your response.

On Fri, Mar 4, 2016 at 1:25 AM, MTGermany <notifications@github.com> wrote:

> Hello Aqiba,
>
> I have forwarded this mail to Arne who runs this website.
>
> Arne: Some links on the page www.movsim.org -> about, for example
> "MovSim JavaDocs", and nearly all of the links on the "examples" page do
> not work (dead link or "denial of response")
>
> Martin
>
> ----------------------------------------------------------
> Dr. Martin Treiber
> Institute for Transport & Economics, TU Dresden
> Chair of Traffic Modelling, Econometrics, and Statistics
> Falkenbrunnen, Room 123 (two floors up from the entrance!)
> Würzburger Str. 35, D-01062 Dresden
> treiber@vwi.tu-dresden.de,
> www.mtreiber.de
> phone/fax: +49 (351) 463 36794 / 36809
> ---------------------------------------------------------
>
> On 03/03/2016 11:36 AM, Aaqiba wrote:
> > These links on your website (http://www.movsim.org/) for
> > MovSim Javadocs (
> >
> http://www.h2063376.stratoserver.net/movsim/version/current/apidocs/index.html
> > )
> > Routing
> > Ramp metering
> > these are not working.
> > help us?
> >
> > On Thu, Mar 3, 2016 at 3:09 PM, MTGermany <notifications@github.com>
> > wrote:
> >
> > > Dear Mr/Ms Aaqiba,
> > >
> > > there is no formal documentation in form of a User's Manual or Tech
> > > Manual. However, Arne Kesting (see the cc) who is the main developer,
> > > surely has some general comments on the global structure. Regarding
> > > details, the code itself is commented, according to the principle "the
> > > truth lies in the code"
> > >
> > > Regards
> > >
> > > Martin
> > >
> > > ----------------------------------------------------------
> > > Dr. Martin Treiber
> > > Institute for Transport & Economics, TU Dresden
> > > Chair of Traffic Modelling, Econometrics, and Statistics
> > > Falkenbrunnen, Room 123 (two floors up from the entrance!)
> > > Würzburger Str. 35, D-01062 Dresden
> > > treiber@vwi.tu-dresden.de,
> > > www.mtreiber.de
> > > phone/fax: +49 (351) 463 36794 / 36809
> > > ---------------------------------------------------------
> > >
> > > On 03/03/2016 07:35 AM, Aaqiba wrote:
> > > >
> > > > Hi! We are beginner in MOVSIM. Can we have documentation of MOVSIM?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/movsim/movsim/issues/32>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/movsim/movsim/issues/32#issuecomment-191692165>.
> > >
> >
> >
> >
> > --
> > Regards
> > Team Learning for Optimal Driver's Personality Profile
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/movsim/movsim/issues/32#issuecomment-191699461>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movsim/movsim/issues/32#issuecomment-191948016>.
>



-- 
Regards
Team Learning for Optimal Driver's Personality Profile

**Comment by akegermany** [comment]
Please generate the Javadoc by yourself directly from the source code. Maven does not work because of errors. So, I recommend creation directly in an IDE like eclipse. 
I'll keep this issue for correcting the javadoc. Moreover I've removed the dead links to the javadoc on the website movsim.org.

Applets on movsim.org are not working due to the fact that Java is not allowed in most 
browsers anymore. You can start the examples directly from the compiled source code.

For general background information about microscopic traffic modeling I'll recommend you to our book, see www.traffic-flow-dynamics.org

Hope that helps you with starting with movsim.

**Comment by akegermany** [comment]
mvn site:site works again for generating javadoc

**Comment by Aaqiba** [comment]
Hi! Sir we are using MOVSIM for our final year project. We are trying to
generate .csv files (output log files) of MOVSIM. We have
developed understanding of MOVSIM source code and log files to some extent.
We have generated .csv files but unable to generate files for 27 vehicles.
We have used the following command to generate log files:
*D:\movsim\movsim-master\core\target\MovsimCore-1.6.0-SNAPSHOT-jar-with-dependencies.jar
-f D:\movsim\movsim-master\core\bookScenarioStartStop\startStop_IDM*
Screen shot of the files is attached below.
We are fail to understand why remaining 22 files for vehicles are not
generated. Would you please help us?


On Sun, Mar 6, 2016 at 8:49 PM, Arne Kesting <notifications@github.com>
wrote:

> Closed #32 <https://github.com/movsim/movsim/issues/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movsim/movsim/issues/32#event-579292677>.
>



-- 
Regards
Team Learning for Optimal Driver's Personality Profile

**Comment by MTGermany** [comment]
Hi Aaqiba,

I did not see any screenshot but I expect that you just got the 
trajectories 2,6,11,16, and 21. The solution is easy: just look at the 
last section of the project control file for this simulation:

startStop_IDM.xprj

There you will find that the xml block  <OutputConfiguration> is 
specified as follows:

         <OutputConfiguration>
             <FloatingCarOutput n_timestep="5" route="main">
                 <FloatingCar number="2" />
                 <FloatingCar number="6" />
                 <FloatingCar number="11" />
                 <FloatingCar number="16" />
                 <FloatingCar number="21" />
             </FloatingCarOutput>
             <Trajectories dt="1" route="main" />
         </OutputConfiguration>

so you will get just the specified trajectories 2,6,11,16, and 21. So it 
is obvious how to add other trajectories, e.g., adding the line

                <FloatingCar number="3" />

somewhere in the vehicle list will give you additionally the trajectory 
of Vehicle 3.

Notice that a dummy such as <FloatingCar number="all" /> does not work, 
you must specify any single trajectory you would like to obtain.

Related to this: In the example, only every 5th simulation time step is 
saved. Since the timestep is set to 0.2 s (you can change it by editing 
the <Simulation> attributes) this means, you get data points every 1.0 
s. If, for example, you would like to have output every 0.1 s (e.g., to 
compare with NGSIM or other data which typically have this frequency), 
set the direct attributes of FloatingCarOutput as

<FloatingCarOutput n_timestep="1" route="main">

(every timestep, all specified  vehicles on the "main" route [here the 
only one] are saved), and the direct <Simulation> attributes as

  <Simulation timestep="0.1" duration="360" seed="42">

I hope this helps.

Martin

----------------------------------------------------------
Dr. Martin Treiber
          Institute for Transport & Economics, TU Dresden
	 Chair of Traffic Modelling, Econometrics, and Statistics
          Falkenbrunnen, Room 123 (two floors up from the entrance!)
          Würzburger Str. 35, D-01062 Dresden
          treiber@vwi.tu-dresden.de,
          www.mtreiber.de
          phone/fax:     +49 (351) 463 36794 / 36809
  ---------------------------------------------------------

**Comment by akegermany** [comment]
Please do not use this issue and channel for bilateral communication. All follower receive notifications and it is not related to this (closed) issue. We have a general email movsim.org@gmail.com and you have Martin's email as well.
