### ISSUE TITLE
I still got some problems to run the program

### ISSUE THREAD

**Issue by beyond1self** [movsim/movsim#51]
Hey ,thank you for replying my dull question. I already installed all the configure files before I submit the issue, it`s my bad not explaining the problem clearly, and I stopped here:

no log4j from commandline provided. Use default log4j configuration from=jar:file:/E:/movsim/movsim/viewer/target/MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar!/config/log4j.properties
option -h. Exit Programm
usage: movsim
 -d,--write_dot                  writes a 'dot' network file for further
                                 analysis of the xodr
 -f,--file <arg>                 movsim main configuration file (ending
                                 ".xprj" will be added automatically if
                                 not provided.
 -h,--help                       prints this message
 -l,--log                        writes the file "log4j.properties" to
                                 file to adjust the logging properties on
                                 an individual level
 -o,--directory <arg>            argument is the output path relative to
                                 calling directory
 -s,--simulation scanning mode   invokes the simulator repeatedly in a
                                 loop (needs to be programmed by user)
 -v,--validate                   parses xml input file for validation
                                 (without simulation)
 -w,--write_xsd                  writes xsd file to output (for
                                 convenience/lookup schema definitions)

I have tried a lot times and looked up many reference materials, and I still can not use these commands correctly......
Can you take some time give me some examples on how to use this commands?
Your program means a lot to me ,exception for your reply.

**Comment by MTGermany** [comment]
Hi,just a quick sequence of commands to verify that you called the program correctly.Go to your movsim directory (it seems to be E:/movsim/movsim/) and enter all the following commands from that directory (the '>' is the prompt of the command line):> java -jar viewer/target/MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar -h => This should produce some help text. The important line(s) are/is the following:-f,--file <arg> movsim main configuration file (ending ".xprj" will be added automatically if not provided) so find any of the provided .xprj directories, e.g., the onramp scenario at sim/buildingBlocks/onramp.xprj and enter:> java -jar viewer/target/MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar -f sim/buildingBlocks/onramp.xprThis should start the simulation and open up a graphical window. If using linux, you can also abbreviate the commands by using shell variables. For example, define your movsim directory with absolute path as a shell variable $movsimdir and the run command by > runViewer="java -jar $movsimdir/viewer/target/MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar"Then, running the above onramp scenario simplifies to the command> $runViewer -f $movsimdir/sim/buildingBlocks/onramp.xprjand you can run it from anywhere on your computer (notice the $ signs denoting the value of the shell variables and the option -f stating that the following is a file to be loaded)All the best,Martin ----------------------------------------------------------Dr. Martin TreiberInstitute for Transport & Economics, TU DresdenChair of Traffic Modelling, Econometrics, and StatisticsFalkenbrunnen, Room 123 (two floors up from the entrance!)Würzburger Str. 35, D-01062 Dresdenmartin@mtreiber.dewww.mtreiber.dephone/fax: +49 (351) 463 36794 / 36809---------------------------------------------------------beyond1self <notifications@github.com> hat am 17. April 2019 um 03:51 geschrieben:  Hey ,thank you for replying my dull question. I already installed all the configure files before I submit the issue, it`s my bad not explaining the problem clearly, and I stopped here:no log4j from commandline provided. Use default log4j configuration from=jar:file:/E:/movsim/movsim/viewer/target/MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar!/config/log4j.properties option -h. Exit Programm usage: movsim -d,--write_dot writes a 'dot' network file for further analysis of the xodr -f,--file movsim main configuration file (ending ".xprj" will be added automatically if not provided. -h,--help prints this message -l,--log writes the file "log4j.properties" to file to adjust the logging properties on an individual level -o,--directory argument is the output path relative to calling directory -s,--simulation scanning mode invokes the simulator repeatedly in a loop (needs to be programmed by user) -v,--validate parses xml input file for validation (without simulation) -w,--write_xsd writes xsd file to output (for convenience/lookup schema definitions)I have tried a lot times and looked up many reference materials, and I still can not use these commands correctly...... Can you take some time give me some examples on how to use this commands? Your program means a lot to me ,exception for your reply.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by beyond1self** [comment]
Thank you very much for your reply. I finally let the program run.
Thank you for taking the time to teach me in such detail !!!
